[package]
name = "aoc2002"
version = "0.1.0"
authors = ["boinc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.22"
regex = "1.4.2"
lazy_static = "1.4.0"
